In [1]:
import pandas as pd

In [7]:
df = pd.read_csv("stocks.csv")
df

,date,ticker,date.1,open,high,low,close,volume,ex-dividend,split_ratio,adj_open,adj_high,adj_low,adj_close,adj_volume,20-Day SMA,100-Day SMA,Volatility,Lag Gap
0,3/27/2018,GOOGL,3/27/2018,1063.90,1064.54,997.62,1006.94,2940957,0.0,1,1063.900000,1064.540000,997.620000,1006.940000,2940957,1006.94000,1006.940000,66.920000,43.660000
1,3/26/2018,GOOGL,3/26/2018,1050.60,1059.27,1010.58,1054.09,3272409,0.0,1,1050.600000,1059.270000,1010.580000,1054.090000,3272409,1054.09000,1054.090000,48.690000,43.660000
2,3/23/2018,GOOGL,3/23/2018,1051.37,1066.78,1024.87,1026.55,2413517,0.0,1,1051.370000,1066.780000,1024.870000,1026.550000,2413517,1026.55000,1026.550000,41.910000,-2.720000
3,3/22/2018,GOOGL,3/22/2018,1080.01,1083.92,1049.64,1053.15,3418154,0.0,1,1080.010000,1083.920000,1049.640000,1053.150000,3418154,1053.15000,1053.150000,34.280000,53.460000
4,3/21/2018,GOOGL,3/21/2018,1092.57,1108.70,1087.21,1094.00,1990515,0.0,1,1092.570000,1108.700000,1087.210000,1094.000000,1990515,1094.00000,1094.000000,21.490000,39.420000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6206,1/8/2010,AAPL,1/8/2010,210.30,212.00,209.06,211.98,15986100,0.0,1,27.026481,27.244955,26.867124,27.242384,111902700,202.80645,29.418733,0.377831,0.024418
6207,1/7/2010,AAPL,1/7/2010,211.75,212.00,209.05,210.58,17040400,0.0,1,27.212826,27.244955,26.865839,27.062465,119282800,203.69945,29.353011,0.379116,-0.029558
6208,1/6/2010,AAPL,1/6/2010,214.38,215.23,210.75,210.97,19720000,0.0,1,27.550818,27.660055,27.084312,27.112585,138040000,204.45545,29.284423,0.575742,0.488353
6209,1/5/2010,AAPL,1/5/2010,214.60,215.59,213.25,214.38,21496600,0.0,1,27.579091,27.706320,27.405597,27.550818,150476200,205.40145,29.220346,0.300723,0.466506
6210,1/4/2010,AAPL,1/4/2010,213.43,214.50,212.38,214.01,17633200,0.0,1,27.428730,27.566240,27.293790,27.503268,123432400,206.15895,29.165727,0.272450,-0.122088